"""SATIM Phase 2 multi-date validation stub.

The validator blocks single-still promotion and classifies candidate persistence
across imagery epochs. It does not download imagery; callers provide comparison
records generated by fixture loaders or future provider adapters.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Iterable, Mapping


@dataclass(frozen=True)
class MultiDateValidationConfig:
    persistence_min: float = 0.65
    disappearance_max: float = 0.35
    min_cross_epoch_comparisons: int = 1
    near_epoch_month_window: int = 3


def clamp01(value: Any) -> float:
    try:
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        return 0.0


def _epoch_to_month_index(epoch: str | None) -> int | None:
    """Parse simple YYYY-MM epoch labels into a comparable month index."""
    if not epoch:
        return None
    match = re.match(r"^(\d{4})-(\d{2})", str(epoch))
    if not match:
        return None
    year = int(match.group(1))
    month = int(match.group(2))
    if month < 1 or month > 12:
        return None
    return year * 12 + month


def classify_epoch_pair(
    current_epoch: str | None,
    comparison_epoch: str | None,
    *,
    near_epoch_month_window: int = 3,
) -> str:
    """Classify epoch relationship for one comparison image."""
    if not current_epoch or not comparison_epoch:
        return "unknown_epoch"
    if current_epoch == comparison_epoch:
        return "same_epoch"
    current_month = _epoch_to_month_index(current_epoch)
    comparison_month = _epoch_to_month_index(comparison_epoch)
    if current_month is not None and comparison_month is not None:
        if abs(current_month - comparison_month) <= near_epoch_month_window:
            return "near_epoch"
    return "cross_epoch"


def validate_candidate_across_dates(
    candidate: Mapping[str, Any],
    comparisons: Iterable[Mapping[str, Any]],
    *,
    config: MultiDateValidationConfig | None = None,
) -> dict[str, Any]:
    """Return a validation patch for one SATIM visual-ledger candidate.

    Each comparison may include:
    - `imagery_epoch`
    - `capture_datetime_utc`
    - `geometry_match_score`
    - `radiometric_match_score`
    """
    cfg = config or MultiDateValidationConfig()
    current_epoch = candidate.get("imagery_epoch")
    comparison_rows = list(comparisons)
    epoch_classes = [
        classify_epoch_pair(
            current_epoch,
            row.get("imagery_epoch"),
            near_epoch_month_window=cfg.near_epoch_month_window,
        )
        for row in comparison_rows
    ]
    cross_epoch_rows = [row for row, klass in zip(comparison_rows, epoch_classes) if klass == "cross_epoch"]

    contradiction_flags: list[str] = list(candidate.get("contradiction_flags") or [])
    source_dates = [row.get("capture_datetime_utc") for row in comparison_rows if row.get("capture_datetime_utc")]

    if "near_epoch" in epoch_classes and len(cross_epoch_rows) < cfg.min_cross_epoch_comparisons:
        return {
            "epoch_class": "near_epoch",
            "multi_date_persistence": 0.0,
            "source_dates_compared": source_dates,
            "decision": "review",
            "classification_hint": candidate.get("classification", "indeterminate"),
            "contradiction_flags": contradiction_flags,
            "review_state": "needs_review",
        }

    if len(cross_epoch_rows) < cfg.min_cross_epoch_comparisons:
        if "single_still_seam_claim" not in contradiction_flags:
            contradiction_flags.append("single_still_seam_claim")
        return {
            "epoch_class": "insufficient_cross_epoch",
            "multi_date_persistence": 0.0,
            "source_dates_compared": source_dates,
            "decision": "cross_source_required",
            "classification_hint": candidate.get("classification", "indeterminate"),
            "contradiction_flags": contradiction_flags,
            "review_state": "needs_review",
        }

    match_scores = [
        0.5 * clamp01(row.get("geometry_match_score")) + 0.5 * clamp01(row.get("radiometric_match_score"))
        for row in cross_epoch_rows
    ]
    persistence = sum(match_scores) / len(match_scores) if match_scores else 0.0

    if persistence >= cfg.persistence_min:
        classification_hint = "probable_ground_feature"
        decision = "cross_source_required"
    elif persistence <= cfg.disappearance_max:
        classification_hint = "mixed_epoch_artifact"
        decision = "review"
    else:
        classification_hint = "indeterminate"
        decision = "review"

    return {
        "epoch_class": "cross_epoch",
        "multi_date_persistence": round(persistence, 4),
        "source_dates_compared": source_dates,
        "decision": decision,
        "classification_hint": classification_hint,
        "contradiction_flags": contradiction_flags,
        "review_state": "needs_review",
    }
